### ISSUE TITLE
AttributeError: module 'os' has no attribute 'mkfifo'

### ISSUE THREAD

**Issue by PrivateThink** [brendano/stanford_corenlp_pywrapper#44]
i got error as follow,how could i do?

Traceback (most recent call last):
  File "G:/paperCode/SA-Sent-master/tokenizer.py", line 5, in <module>
    proc = CoreNLP("ssplit", corenlp_jars=["data/stanford-corenlp-full-2018-02-27/*"])
  File "C:\software\Python35\lib\site-packages\stanford_corenlp_pywrapper\sockwrap.py", line 151, in __init__
    self.start_server()
  File "C:\software\Python35\lib\site-packages\stanford_corenlp_pywrapper\sockwrap.py", line 170, in start_server
    os.mkfifo(self.outpipe)
AttributeError: module 'os' has no attribute 'mkfifo'

**Comment by brendano** [comment]
This might be due to Windows?  I don't advise using this software anymore.
